// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "project_goldfishProjectile.generated.h"

class USphereComponent;
class UProjectileMovementComponent;

/**
 * Aproject_goldfishProjectile:
 * 
 * Represents a projectile fired by the player or other actors.
 * Handles collision and movement logic.
 */
UCLASS(config=Game)
class Aproject_goldfishProjectile : public AActor
{
	GENERATED_BODY()

	/** Sphere collision component used to detect hits with other actors */
	UPROPERTY(VisibleDefaultsOnly, Category=Projectile)
	USphereComponent* CollisionComp;

	/** Component responsible for moving the projectile */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = Movement, meta = (AllowPrivateAccess = "true"))
	UProjectileMovementComponent* ProjectileMovement;

public:
	// Constructor
	Aproject_goldfishProjectile();

	/**
	 * Called when the projectile hits another object.
	 *
	 * @param HitComp - The component of this projectile that collided
	 * @param OtherActor - The actor that was hit
	 * @param OtherComp - The component of the hit actor
	 * @param NormalImpulse - The impulse generated by the hit
	 * @param Hit - Detailed hit result
	 */
	UFUNCTION()
	void OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);

	/** Getter for the collision component */
	USphereComponent* GetCollisionComp() const { return CollisionComp; }

	/** Getter for the projectile movement component */
	UProjectileMovementComponent* GetProjectileMovement() const { return ProjectileMovement; }
};
